### ISSUE TITLE
Duplicate counting of AVX2 and AVX512 ?

### ISSUE THREAD

**Issue by EthanZHF** [clearlinux/clr-avx-tools#10]
Hi,
   I am here to bother you know :)
   I added some code to debug the likely duplicate counting, given the position I patched right, if I am wrong, please correct me.

  I cloned the code from the git repo and make install .
  
 # git clone https://github.com/clearlinux/clr-avx-tools.git
 # make install

 patched avxjudge.py  with following debug.patch

 /usr/share/clr-avx-tools # diff avxjudge.py avxjudge.py.patched
184a185,187
> sse_avx2_duplicate_cnt = 0
> avx2_avx512_duplicate_cnt = 0
> 
191a195,196
>     global sse_avx2_duplicate_cnt
>     global avx2_avx512_duplicate_cnt
235a241,248
>   
>     if sse_score >=0.0 and avx2_score >= 0.0:
>         sse_avx2_duplicate_cnt +=1
>         print("duplicate count for sse & avx2 ?", ins, arg, 
> sse_avx2_duplicate_cnt)
> 
>     if avx512_score >= 0.0 and avx2_score >= 0.0:
>         avx2_avx512_duplicate_cnt +=1
>         print("duplicate count for avx2 & avx512 ?", ins, arg, 
> avx2_avx512_duplicate_cnt)
262a276,277
> 
>     print("File duplicate count of sse&avx2", sse_avx2_duplicate_cnt, 
> ", duplicate count of avx2&avx512", avx2_avx512_duplicate_cnt);

score the /usr/lib64/avxstatus/openblas_clr/libopenblas_skylakexp-r0.3.3.so with patched avxjudge.py.patched

# python3 avxjudge.py.patched  /usr/lib64/avxstatus/openblas_clr/libopenblas_skylakexp-r0.3.3.so

we can see following output 

…..
duplicate count for sse & avx2 ? vfmadd132sd 0x15473f(%rip),%xmm3,%xmm1         66799
duplicate count for sse & avx2 ? vextractf64x2 $0x1,%ymm0,%xmm1 66800 duplicate count for avx2 & avx512 ? vextractf64x4 $0x1,%zmm0,%ymm0 11497 duplicate count for sse & avx2 ? vextractf64x2 $0x1,%ymm0,%xmm0 66801 duplicate count for sse & avx2 ? vextractf64x2 $0x1,%ymm0,%xmm1 66802 duplicate count for avx2 & avx512 ? vextractf64x4 $0x1,%zmm0,%ymm0 11498 duplicate count for sse & avx2 ? vextractf64x2 $0x1,%ymm0,%xmm0 66803 duplicate count for sse & avx2 ? vextractf64x2 $0x1,%ymm0,%xmm1 66804 duplicate count for avx2 & avx512 ? vextractf64x4 $0x1,%zmm0,%ymm0 11499 duplicate count for sse & avx2 ? vextractf64x2 $0x1,%ymm0,%xmm0 66805 duplicate count for sse & avx2 ? vextractf128 $0x1,%ymm0,%xmm1 66806 duplicate count for avx2 & avx512 ? vextractf32x8 $0x1,%zmm0,%ymm0 11500 duplicate count for sse & avx2 ? vextractf128 $0x1,%ymm0,%xmm0 66807 duplicate count for sse & avx2 ? vextractf128 $0x1,%ymm0,%xmm1 66808 duplicate count for avx2 & avx512 ? vextractf32x8 $0x1,%zmm0,%ymm0 11501 duplicate count for sse & avx2 ? vextractf128 $0x1,%ymm0,%xmm0 66809 duplicate count for sse & avx2 ? vextractf128 $0x1,%ymm0,%xmm1 66810 duplicate count for avx2 & avx512 ? vextractf32x8 $0x1,%zmm0,%ymm0 11502 duplicate count for sse & avx2 ? vextractf128 $0x1,%ymm0,%xmm0 66811
duplicate count for sse & avx2 ? vfmadd231ss 0x436(%rip),%xmm1,%xmm0         66812
duplicate count for sse & avx2 ? vfmadd231sd 0x5e7(%rip),%xmm1,%xmm0         66813
Top SSE functions by instruction count
    sgetrf_single@@Base                 87.5 %s
    slaed6_@@Base                       86.79 %s
    dlaed6_@@Base                       86.79 %s
    slasd6_@@Base                       84.89 %s
    dlasd6_@@Base                       84.89 %s

Top SSE functions by value
    clarfy_@@Base                       2076.4
    cgemm3m_oncopyr@@Base               1504.61
    cgemm3m_oncopyi@@Base               1459.66
    csymm3m_iucopyb@@Base               1459.66
    zgemm_kernel_b@@Base                1389.3

Top AVX2 functions by instruction count
    zgemm_incopy@@Base                  49.48 %s
    zgemm_kernel_b@@Base                49.24 %s
    cgemm_incopy@@Base                  49.15 %s
    zgemm_kernel_r@@Base                49.11 %s
    zgemm_kernel_l@@Base                49.11 %s

Top AVX2 functions by value
    cgemm_kernel_b@@Base                3439.4
    cgemm_incopy@@Base                  3439.4
    cgemm_kernel_r@@Base                3439.16
    cgemm_kernel_l@@Base                3439.16
    zgemm_kernel_b@@Base                3190.86

Top AVX512 functions by instruction count
    zgemm_itcopy@@Base                  57.67 %s
    zgemm3m_oncopyr@@Base               52.59 %s
    zgemm3m_oncopyi@@Base               51.9 %s
    zsymm3m_iucopyb@@Base               51.73 %s
    cgemm_otcopy@@Base                  43.35 %s

Top AVX512 functions by value
    zgemm3m_oncopyr@@Base               1952.7
    cgemm3m_oncopyr@@Base               1703.05
    zgemm3m_oncopyi@@Base               1389.69
    zsymm3m_iucopyb@@Base               1389.54
    csymm3m_iucopyb@@Base               1251.03

File total (SSE):  542451 instructions with score 126060 File total (AVX2):  114279 instructions with score 112833 File total (AVX512):  80538 instructions with score 30653

File duplicate count of sse&avx2 66813 , duplicate count of avx2&avx512 11502

Please take a look.

The debug.patch and the output log are attached.

Thanks,
Ethan
[duplicate_count.log.tar.gz](https://github.com/clearlinux/clr-avx-tools/files/2564939/duplicate_count.log.tar.gz)

**Comment by EthanZHF** [comment]
Debug.patch missed ? attach it again. seems github doesn't support .patch format.

[debug.zip](https://github.com/clearlinux/clr-avx-tools/files/2564947/debug.zip)

**Comment by thiagomacieira** [comment]
If you have a fix, please push it to your clone here on GitHub and create a pull request.

**Comment by EthanZHF** [comment]
Please pull from 



https://github.com/EthanZHF/clearlinux-clr-avx-tools/commits/master

commit f0ea1dd247a9054fe4e6d1fabe30ffebeaa3669e
avxjudge.py: Add -d debug command line option

commit 3df030c6a4570f9f92a3e53eb7b70ce232f2647e
avxjudge.py: fix duplicate counting of AVX2&AVX512 or SSE&AVX2

**Comment by thiagomacieira** [comment]
Hello @EthanZHF 

Can you use GitHub's pull request feature? You already have the commits in GitHub, just click the necessary buttons to create the PR.

**Comment by EthanZHF** [comment]
Yup :)
I am trying to get it done in GitHub PR.

**Comment by EthanZHF** [comment]
Hi @thiagomacieira 
  I have no access right to push my branch into this repo,  my account is a personal one,  only could create PR for my own clone repo.
 Could you help to create a PR for me ? Or how could I push my branch into this repo then create PR?

Thanks,
Ethan

**Comment by EthanZHF** [comment]
Done, fork first then create PR.

**Comment by thiagomacieira** [comment]
Fixed by #11
