### ISSUE TITLE
found avxjudg.py takes callq/jmp as AVX2 

### ISSUE THREAD

**Issue by EthanZHF** [clearlinux/clr-avx-tools#12]
Found script takes following jmp/callq instructions as AVX2
    while doing libopenblas_nehalemp-r0.3.3.so with '-d' option
    
     ...
     AVX2 instruction ? jmp    39092d <zsymm3m_olcopyi@@Base+0x1f8d>
     AVX2 instruction ? jl     39092a <zsymm3m_olcopyi@@Base+0x1f8a>
     AVX2 instruction ? jne    3909d8 <zsymm3m_olcopyi@@Base+0x2038>
     AVX2 instruction ? jg     390a20 <zsymm3m_olcopyi@@Base+0x2080>
     AVX2 instruction ? jmpq   38ef4e <zsymm3m_olcopyi@@Base+0x5ae>
     AVX2 instruction ? callq  857c0 <ssymm_@plt>
     AVX2 instruction ? je     390aa1 <zsymm3m_olcopyi@@Base+0x2101>
     ...
    
     File total (SSE):  555391 instructions with score 208750
     File total (AVX2):  3834 instructions with score 38 <--false report
     File total (AVX512):  0 instructions with score 0

Will file another PR with two patches to fix it.

**Comment by phmccarty** [comment]
Fixed with #14
